# Generated by Django 4.1.6 on 2023-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_1', models.URLField()),
                ('img_2', models.URLField()),
                ('img_3', models.URLField()),
                ('story', models.TextField()),
                ('artist_painting_1', models.URLField()),
                ('artist_painting_2', models.URLField()),
                ('artist_painting_3', models.URLField()),
                ('artist_painting_1_title', models.CharField(max_length=200)),
                ('artist_painting_2_title', models.CharField(max_length=200)),
                ('artist_painting_3_title', models.CharField(max_length=200)),
                ('correct_answer', models.IntegerField(default=0)),
                ('incorrect_answer', models.IntegerField(default=0)),
            ],
        ),
    ]
