# Generated by Django 4.1.6 on 2023-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_1_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_2_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_painting_3_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='story',
            field=models.TextField(blank=True, default=''),
        ),
    ]
