# Generated by Django 4.1.6 on 2023-07-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_artist_artist_painting_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='famous_work',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='portrait',
            field=models.URLField(blank=True, default=''),
        ),
    ]
